use crate::adapter::openai_resp::resp_types::RespUsage;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use serde_with::{serde_as, skip_serializing_none};

fn default_response_status() -> String {
	"completed".to_string()
}

/// DOC: https://platform.openai.com/docs/api-reference/responses/object
///
/// NOTE: Not all OpenAI Responses Response properties have been set in this struct.
///       Mostly what is needed for the Chat Completion compatibility.
#[serde_as]
#[skip_serializing_none]
#[derive(Default, Debug, Clone, Serialize, Deserialize)]
pub struct RespResponse {
	/// Unique identifier for this Response.
	pub id: String,

	/// The status of the response generation. One of completed, failed, in_progress, cancelled, queued, or incomplete.
	#[serde(default = "default_response_status")]
	pub status: String,

	/// {code: String, message: string}
	pub error: Option<Value>,

	/// An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens.
	pub max_output_tokens: Option<i64>,

	/// Model ID used to generate the response, like gpt-4o or o3.
	pub model: String,

	/// An array of content items generated by the model.
	pub output: Vec<Value>,

	pub usage: Option<RespUsage>,
}

#[cfg(test)]
mod tests {
	use super::*;
	use serde_json::json;

	#[test]
	fn response_without_status_defaults_to_completed() {
		let response: RespResponse = serde_json::from_value(json!({
			"id": "msg_011Cd1jKFkLVE1QPgvXNsmUG",
			"error": null,
			"max_output_tokens": null,
			"model": "claude-opus-4-8",
			"output": [{
				"type": "function_call",
				"call_id": "toolu_01UmvRQFrZEoyiPTcQDznGeK",
				"name": "linkup-search",
				"arguments": "{\"query\":\"example\"}"
			}],
			"usage": null
		}))
		.expect("response without status should deserialize");

		assert_eq!(response.status, "completed");
		assert_eq!(response.output.len(), 1);
	}
}
